### PR TITLE
Update to related_docs.rst

### PR DESCRIPTION
**Pull request by ehsteve**
Added links to other relevant documents

### CODE REVIEW

**Comment by tonyastrofig** [comment]
@ehsteve, are these just boiler plate document references?

**Comment by ehsteve** [comment]
SPD-41 is the policy document that drives the HPD policy. It's not completely required to list but I thought it worthwhile. I also added the CMAD template because that is what i used in our doc structure.

**Review by dbarrous — APPROVED** [review]
LGTM!

**Review by tonyastrofig — APPROVED** [review]
Looks good to me

**Pull request merged**
